### ISSUE TITLE
Add API connector for Syriaca.org keywords

### ISSUE THREAD

**Issue by nathangibson** [usaybia/tei-publisher-vscode#3]
@wsalesky Does the Syriaca.org API serve up keywords from https://syriaca.org/taxonomy ? (I can't seem to test this at the moment as I'm getting the error `HTTP ERROR 405 HTTP method GET is not supported by this URL` on any API requests to Syriaca, e.g., https://syriaca.org/api/search/persName?q=Peter)

If this is already built-in, could we please add an API connector for it to the VS Code extension? For Usaybia, we use Syriaca keywords rather than having our own module. 

Thanks!

**Comment by wsalesky** [comment]
@wsalesky Yes it does search the taxonomy, however the REST API is not set up yet, I was having too many issues just keeping the server stable. However, it has been running nicely for a week now, so I will go ahead and get the REST API working as well as the SPARQL endpoint. Will let you know when it is up.

**Comment by wsalesky** [comment]
@nathangibson Sorry for the delay, the REST API is now working on Syriaca.org. I think I need to add the terms to the API connector.

**Comment by wsalesky** [comment]
@nathangibson Actually keywords should already work. Let me know if not.

**Comment by nathangibson** [comment]
Thanks @wsalesky ! Is "title" the correct path? E.g., this seems to work https://syriaca.org/api/search/title?q=Copts

Could you please add "Syriaca keywords" as an option to the Usaybia VSCode plugin? Should I reopen this issue?

**Comment by wsalesky** [comment]
Title will work, but most likely you will want [https://syriaca.org/api/search/term?q=Copts](https://syriaca.org/api/search/term?q=Copts). Also this is already in the Usaybia VSCode plugin. The dropdown has places, persons and terms but currently only searches usyabia.org. Do you want to add a syriaca.org option for persons and places as well?

**Comment by nathangibson** [comment]
Ahh, thanks for the clarification. 

Right, what I'd like for the _keyword_ option (not the others) is for the plugin to search Syriaca.org for keywords and insert a Syriaca.org URI (just the URI, no extra tags at this point). 

For Usaybia, we're relying on Syriaca keywords rather than developing our own.

**Comment by wsalesky** [comment]
@nathangibson Just to clarify what do you mean by no extra tags? Using the current pattern, selecting a term will result in the selected text being wrapped in a tei:term element:  `<term ref="http://syriaca.org/term/termID">TERM</term>`  Is this not what you had in mind?

**Comment by nathangibson** [comment]
@wsalesky Because we'll be using the keywords mostly when writing factoids, I think our use case (unlike persons and places) will not be wrapping a portion of text with a tag but rather searching for the term in the sidebar and inserting the URI into the relevant spot in the factoid. So we'll want to just insert the bare URI, e.g., `http://syriaca.org/term/termID`. Is this hard to change?

**Comment by wsalesky** [comment]
Okay, can you give this version a try? This pull request also addresses: #2

**Comment by nathangibson** [comment]
@wsalesky Sorry, this fell off my radar. 

We're having problems getting the new version of this extension installed/working at all. The VSIX file seems to have disappeared. Is there a different way we should be installing? 

~~Even if we try to install from the old file https://github.com/usaybia/tei-publisher-vscode/blob/546c56ef9c8fb41c93e03b3609ea4d1c984d28c6/tei-publisher-vscode-1.0.0.vsix the search function produces 0 results with this (the same searches produce multiple results for people who had pre-installed older versions).~~

**Comment by wsalesky** [comment]
@nathangibson Sorry, was on vacation last week. Please try the DropBox version and let me know if it works. I will troubleshoot what is going on in GitHub.

**Comment by nathangibson** [comment]
@wsalesky Works perfectly, including the keyword terms. Thanks! 

Please ignore the above part about not returning any results. That appears to be a general conflict between the TEI Publisher extension and VS Code 1.57, see https://github.com/eeditiones/tei-publisher-vscode/issues/7.

**Comment by wsalesky** [comment]
Okay, great! I will work on getting the code on GitHub, however the safest way to use it is to build it locally. I have had trouble with GitHub and packages in the past, although this may be resolved by making sure to increment the version # every time. We shall see.

**Comment by nathangibson** [comment]
Thanks, I don't have experience with building it locally, I take it this is using npm?

**Comment by wsalesky** [comment]
I will post instructions on how to build it. (I have to look them up every time since I don't do it often enough to remember!)
