### ISSUE TITLE
Pull in fix from tei-publisher

### ISSUE THREAD

**Issue by nathangibson** [usaybia/tei-publisher-vscode#5]
@wsalesky Could you please pull in the upstream fix (see https://github.com/eeditiones/tei-publisher-vscode/issues/7) from tei-publisher-vscode? 

This is fairly high priority since it affects are tagging work, but hopefully not hard. Thanks!

**Comment by wsalesky** [comment]
@nathangibson Can you give the sropheAuthority-vscode-1.0.3.vsix package a try? Also to build this yourself you simply need to run: 

`vsce package `

In the root directory. (The version number is tracked in the package.json file)

**Comment by nathangibson** [comment]
@wsalesky The plugin seems to be working perfectly now with 1.57.1. Thanks!

Only thing is the Usaybia API itself is returning 0 results. Should I rerun the index?

**Comment by nathangibson** [comment]
> Also to build this yourself you simply need to run:
> 
> `vsce package `
> 
> In the root directory. (The version number is tracked in the package.json file)

For documentation purposes, here's what I did: 
1. Installed Node.js (npm, using homebrew)
2. Installed VSCE `$ npm install -g vsce` (see https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce)
3. Installed webpack `$ npm install webpack` (got an error message when I tried to build without it)
4. Built with `$ vsce package`. This did indeed build a vsix package.

**Comment by wsalesky** [comment]
@nathangibson what search is returning empty? Another way to test if it is the API or the plugin is to search the API directly:
https://usaybia.net/api/search/placeName?q=Abdera

This returns empty, so I think there is a problem with the index. Try re-indexing.

**Comment by nathangibson** [comment]
Thanks, that worked!
