### ISSUE TITLE
0 results returned in search sidebar

### ISSUE THREAD

**Issue by nathangibson** [usaybia/tei-publisher-vscode#7]
@wsalesky When it rains it pours ...

Not sure yet if this is related to my having reinstalled the app on the server, but we're now getting 0 results for searches in the VS Code plugin (whether manually typed in or via selecting text and CMD+Shift+E). The strange thing is, the API is working correctly, e.g., https://usaybia.net/api/search/placeName?q=Damascus returns 2 hits but searching for "Damascus" in the VSC plugin returns "Found 0 items." 

I get this in VSC 1.60 with sropheAuthority-vscode v1.0.3 but also when I tried downgrading to VSC 1.56. (Just updated my OS to Mac 11.6 but since this is also affecting others, I don't think that's it.) 

@LukasFrosch , since you have the same problem, which VSC version and OS version are you running? 

@hannafriedel Do you have this problem too? 

I know you have several things going right now, so if you think it'll take a while to fix, let me know and I'll reassign the people who are using this right now to other tasks. Thanks!

**Comment by wsalesky** [comment]
@nathangibson I can verify that it no longer works on my machine and I have upgraded nothing in a very long time. So, I would suspect the culprit is not the plugin, but the connection. Is there a firewall? Could that be blocking the request? Nevermind, I can send a request to the API locally. I will see what I can find out. It is odd.

**Comment by wsalesky** [comment]
@nathangibson Also, when was this last working? (Just in case it is related to the extended syriaca.org downtime.)

**Comment by nathangibson** [comment]
> @nathangibson I can verify that it no longer works on my machine and I have upgraded nothing in a very long time. So, I would suspect the culprit is not the plugin, but the connection. Is there a firewall? Could that be blocking the request? Nevermind, I can send a request to the API locally. I will see what I can find out. It is odd.

I just tried a connection setting that might bypass the firewall, but no change. Otherwise I'll have to do a deeper dive. So you think at this point it is or isn't the firewall?

**Comment by nathangibson** [comment]
> @nathangibson Also, when was this last working? (Just in case it is related to the extended syriaca.org downtime.)

Found out about it this morning (that's why I was wondering if it was related to my reinstalling the docker image on the server yesterday). @LukasFrosch How long has it not been working for you?

**Comment by nathangibson** [comment]
For what it's worth, the original TEI-Publisher extension (v1.1.1) does work.

**Comment by nathangibson** [comment]
Not sure how long it hasn't been working since we weren't using it for a couple weeks.

**Comment by nathangibson** [comment]
This appears to be fixed now. 

Could it have had something to do with the Syriaca.org downtime, since it does query Syriaca for the taxonomy terms? The terms search is still not returning results (API down, see srophe/srophe-eXist-app/issues/1265) but perhaps if it gets a certain kind of error/times out it doesn't proceed with any of the lookups? 

Anyway, glad it seems to have resolved itself.

**Comment by wsalesky** [comment]
@nathangibson Yes, I think it  must have been getting hung up while waiting for a response from Syriaca.org. Seems like a bug to me, one failed endpoint should not cause the others to fail. Will have to look into it at a later date and see if there is a way to avoid that.
